### ISSUE TITLE
labels of the data

### ISSUE THREAD

**Issue by liuchenxjtu** [blebreton/spark-FM-parallelSGD#2]
Hi,
   thanks for your work. but I wondered why the label must be -1 or 1? in the original implementation I did not find such requirements.

**Comment by blebreton** [comment]
Hi,

For the mathematics, it’s MUCH more convenient to have the -1 and 1 labels. You can rewrite the formula’s with 0 labels but it becomes very complicated then.
However, that's right that it’s often common to use 0/1 labels. In the documentation of MLLIB (http://spark.apache.org/docs/latest/mllib-linear-methods.html ) is written that they use -1/1 for the mathematics, but 0/1 in the api because it’s more common.
It’s a small change for our implementation to also accommodate this, since there’s already a function to change the labeling (tansform_data(data_rdd)).
