### ISSUE TITLE
Problem integer features criteo dataset

### ISSUE THREAD

**Issue by martijnnanne** [blebreton/spark-FM-parallelSGD#5]
Hi, I'm testing the algorithm on the criteo dataset. The dataset contains both categorical variables and integers (as opposed to the a9a dataset) and it seems that the algorithm is not working correctly. In the function  fm_gradient_sgd_trick, the exponyt variable becomes inf whereafter the result matrix becomes all NaN.

We also noticed that the bias weight and the first order interactions are left out, maybe this could be the problem?

Do you know what might be the problem?

**Comment by dafnevk** [comment]
It seems like a numerical overflow. It might help to normalize the numerical values first (and possibly log-transform them).

**Comment by blebreton** [comment]
Hi Martijn,

Dafne is right. You could normalize / log-transform numerical values to avoid NaN / inf.
For categorical values, you could use one-hot encoding to convert them into numerical values. (You could also apply one-hot encoding to numerical values by the way). Or you could try to apply a hash function.

You might be interested in looking at the wining solution of the kaggle criteo competition : https://www.kaggle.com/c/criteo-display-ad-challenge/forums/t/10555/3-idiots-solution-libffm

Note that FM works well with sparse features (like a9a dataset).

Bias weight and the first order interactions are left out because FM already considers interactions a lot. It would not contribute much to the model and calculation of the second term is time consuming. It is not the cause of your problem.

Benjamin

**Comment by fooSynaptic** [comment]
I encountered by the same problem, while there exists a computation method to remit the pain of numeric instability: [logsum of loss](https://github.com/fooSynaptic/NLP_utils/blob/cf352d0124b86fab91cbc9f700c82ab398f15905/ML/PGM/CRF/crf_from_scratch/utils.py#L105)
